---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus-aks
  namespace: core-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-aks
  namespace: core-monitor

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-core
  namespace: core-monitor
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 15s

    scrape_configs:
      - job_name: 'prometheus'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'prometheus'
          action: keep

      # 采集node exporter监控数据
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - source_labels: [__address__]
          action: replace
          regex: ([^:]+):.*
          replacement: $1:9100
          target_label: __address__
        - source_labels: [__meta_kubernetes_node_name]
          regex: 'virtual-node-aci-linux'
          action: drop

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: core-monitor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard-lrs-azurefile
  resources:
    requests:
      storage: 500Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-core
  namespace: core-monitor
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus-main
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-aks
      containers:
      - name: prometheus
        image: prom/prometheus:v2.38.0
        command:
          - "/bin/prometheus"
        args:
          - '--storage.tsdb.retention=30d'
          - '--config.file=/etc/prometheus/prometheus.yaml'
          - '--storage.tsdb.path=/etc/prometheus-data'
          - '--web.enable-lifecycle'
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data-volume
          mountPath: /etc/prometheus-data
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-core
      - name: data-volume
        persistentVolumeClaim:
          claimName: prometheus-data

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: core-monitor
  labels:
    app: prometheus
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  type: ClusterIP