apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: logs-fleet-server
  namespace: core-monitor
spec:
  version: 8.4.3
  kibanaRef:
    name: logs-kibana-cluster
    namespace: core-monitor
  elasticsearchRefs:
  - name: logs-es-cluster
    namespace: core-monitor
  mode: fleet
  fleetServerEnabled: true
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: logs-elastic-agent
  namespace: core-monitor
spec:
  version: 8.4.3
  kibanaRef:
    name: logs-kibana-cluster
    namespace: core-monitor
  fleetServerRef:
    name: logs-fleet-server
    namespace: core-monitor
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: core-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent
subjects:
- kind: ServiceAccount
  name: elastic-agent
  namespace: core-monitor
roleRef:
  kind: ClusterRole
  name: elastic-agent
  apiGroup: rbac.authorization.k8s.io