apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: logs-kibana-cluster
  namespace: core-monitor
spec:
  version: 8.4.3
  count: 1
  elasticsearchRef:
    name: logs-es-cluster
    namespace: core-monitor
  config:
    server.publicBaseUrl: kibana.local.sz
    xpack.fleet.agents.elasticsearch.hosts: ["https://logs-es-cluster-es-http.core-monitor.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://logs-fleet-server-agent-http.core-monitor.svc:8220"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        is_default_fleet_server: true
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        is_default: true
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
  http:
    tls:
      selfSignedCertificate:
        disabled: true
