---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-core
  namespace: core-monitor
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['prometheus:9090']

      # 采集node exporter监控数据
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - source_labels: [__address__]
          action: replace
          regex: ([^:]+):.*
          replacement: $1:9100
          target_label: __address__
        - source_labels: [__meta_kubernetes_node_name]
          regex: 'virtual-node-aci-linux'
          action: drop

      # 采集kube-state-metrics监控数据
      - job_name: 'kube-state-exporter'
        static_configs:
        - targets: ['kube-state-metrics:8080']