---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: core-monitor
  labels:
    app: prometheus
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  type: ClusterIP