name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: mcs-dapr-poc-frontend
      run: docker build . --file Dockerfile --tag mcs-dapr-poc-frontend:$(date +%s)
