name: POC Frontend Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: mcs-dapr-poc-frontend
      run: docker build . --file Dockerfile --tag daprdemo.azurecr.io\mcs-dapr-poc-frontend:${{ github.run_id }}
      
    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login Azure ACR & push image
      run: |
        az acr login --name daprdemo
        docker push daprdemo.azurecr.io\mcs-dapr-poc-frontend:${{ github.run_id }}
        
